### ISSUE TITLE
vulnerabilities 

### ISSUE THREAD

**Issue by IssaGithub** [DeborahK/Angular-RxJS#48]
Hi Deborah
after instaling APM-START and APM-FINAL, follwing vulnerabilities were found
![image](https://user-images.githubusercontent.com/10864164/194218783-2f92bbd2-7e99-400a-ab92-43215ea1e1d3.png)

Just wanted to inform you. Maybe you can update the required packages.

**Comment by DeborahK** [comment]
Thanks for your message.

These are often not an issue because they are in packages (such as testing) that are never deployed.

Normally, it's best not to use `npm audit fix` to fix these packages because it may update some that are then not compatible to other packages that Angular uses.

The Angular team tries to keep up with this, so in a "real" project, continuing to update to the most recent version of Angular often resolves these issues. (I can't easily do that in this case without redoing the course to match.)

**Comment by IssaGithub** [comment]
You could try this
https://www.npmjs.com/package/npm-force-resolutions
I actually updated only the mentioned Package to the next major Version.

**Comment by DeborahK** [comment]
Yeah, I tried setting specific versions early on, then ran into a case where the version of some supporting package was removed due to a critical issue and the install *completely* didn't work.

I assume it's better to have the install work and provide some vulnerability issues (especially since we never deploy this), than to have it not work at all due to a missing package.🤷‍♀️
